// Code generated by protoc-gen-go.
// source: pb/dwork.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/dwork.proto

It has these top-level messages:
	Results
	WorkUnit
	Success
	WorkerID
	Job
	JobParams
	JobStatuses
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Results struct {
	JobID    string `protobuf:"bytes,1,opt,name=JobID" json:"JobID,omitempty"`
	WorkID   int64  `protobuf:"varint,2,opt,name=WorkID" json:"WorkID,omitempty"`
	Found    bool   `protobuf:"varint,3,opt,name=Found" json:"Found,omitempty"`
	Location int64  `protobuf:"varint,4,opt,name=Location" json:"Location,omitempty"`
}

func (m *Results) Reset()                    { *m = Results{} }
func (m *Results) String() string            { return proto.CompactTextString(m) }
func (*Results) ProtoMessage()               {}
func (*Results) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Results) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *Results) GetWorkID() int64 {
	if m != nil {
		return m.WorkID
	}
	return 0
}

func (m *Results) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *Results) GetLocation() int64 {
	if m != nil {
		return m.Location
	}
	return 0
}

// The response message containing the greetings
// https://developers.google.com/protocol-buffers/docs/proto3
type WorkUnit struct {
	JobID     string `protobuf:"bytes,1,opt,name=JobID" json:"JobID,omitempty"`
	ID        int64  `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	Offset    int64  `protobuf:"varint,3,opt,name=Offset" json:"Offset,omitempty"`
	Size      int64  `protobuf:"varint,4,opt,name=Size" json:"Size,omitempty"`
	Status    int64  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	Timestamp int64  `protobuf:"varint,6,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Code      string `protobuf:"bytes,7,opt,name=Code" json:"Code,omitempty"`
}

func (m *WorkUnit) Reset()                    { *m = WorkUnit{} }
func (m *WorkUnit) String() string            { return proto.CompactTextString(m) }
func (*WorkUnit) ProtoMessage()               {}
func (*WorkUnit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WorkUnit) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *WorkUnit) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *WorkUnit) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *WorkUnit) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *WorkUnit) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *WorkUnit) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *WorkUnit) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Success struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *Success) Reset()                    { *m = Success{} }
func (m *Success) String() string            { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()               {}
func (*Success) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Success) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type WorkerID struct {
	UUID string `protobuf:"bytes,1,opt,name=UUID" json:"UUID,omitempty"`
}

func (m *WorkerID) Reset()                    { *m = WorkerID{} }
func (m *WorkerID) String() string            { return proto.CompactTextString(m) }
func (*WorkerID) ProtoMessage()               {}
func (*WorkerID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WorkerID) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type Job struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=Code" json:"Code,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type JobParams struct {
}

func (m *JobParams) Reset()                    { *m = JobParams{} }
func (m *JobParams) String() string            { return proto.CompactTextString(m) }
func (*JobParams) ProtoMessage()               {}
func (*JobParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type JobStatuses struct {
	Statuses []*JobStatuses_JobStatus `protobuf:"bytes,1,rep,name=Statuses" json:"Statuses,omitempty"`
}

func (m *JobStatuses) Reset()                    { *m = JobStatuses{} }
func (m *JobStatuses) String() string            { return proto.CompactTextString(m) }
func (*JobStatuses) ProtoMessage()               {}
func (*JobStatuses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *JobStatuses) GetStatuses() []*JobStatuses_JobStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type JobStatuses_JobStatus struct {
	Name     string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Shards   int64  `protobuf:"varint,2,opt,name=Shards" json:"Shards,omitempty"`
	Found    bool   `protobuf:"varint,3,opt,name=Found" json:"Found,omitempty"`
	Location string `protobuf:"bytes,4,opt,name=Location" json:"Location,omitempty"`
}

func (m *JobStatuses_JobStatus) Reset()                    { *m = JobStatuses_JobStatus{} }
func (m *JobStatuses_JobStatus) String() string            { return proto.CompactTextString(m) }
func (*JobStatuses_JobStatus) ProtoMessage()               {}
func (*JobStatuses_JobStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *JobStatuses_JobStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobStatuses_JobStatus) GetShards() int64 {
	if m != nil {
		return m.Shards
	}
	return 0
}

func (m *JobStatuses_JobStatus) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *JobStatuses_JobStatus) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func init() {
	proto.RegisterType((*Results)(nil), "pb.Results")
	proto.RegisterType((*WorkUnit)(nil), "pb.WorkUnit")
	proto.RegisterType((*Success)(nil), "pb.Success")
	proto.RegisterType((*WorkerID)(nil), "pb.WorkerID")
	proto.RegisterType((*Job)(nil), "pb.Job")
	proto.RegisterType((*JobParams)(nil), "pb.JobParams")
	proto.RegisterType((*JobStatuses)(nil), "pb.JobStatuses")
	proto.RegisterType((*JobStatuses_JobStatus)(nil), "pb.JobStatuses.JobStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Dwork service

type DworkClient interface {
	// Sends a greeting
	GiveWork(ctx context.Context, in *WorkerID, opts ...grpc.CallOption) (*WorkUnit, error)
	ReceiveResults(ctx context.Context, in *Results, opts ...grpc.CallOption) (*Success, error)
	SubmitJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Success, error)
	GetAllJobs(ctx context.Context, in *JobParams, opts ...grpc.CallOption) (*JobStatuses, error)
}

type dworkClient struct {
	cc *grpc.ClientConn
}

func NewDworkClient(cc *grpc.ClientConn) DworkClient {
	return &dworkClient{cc}
}

func (c *dworkClient) GiveWork(ctx context.Context, in *WorkerID, opts ...grpc.CallOption) (*WorkUnit, error) {
	out := new(WorkUnit)
	err := grpc.Invoke(ctx, "/pb.Dwork/GiveWork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dworkClient) ReceiveResults(ctx context.Context, in *Results, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := grpc.Invoke(ctx, "/pb.Dwork/ReceiveResults", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dworkClient) SubmitJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := grpc.Invoke(ctx, "/pb.Dwork/SubmitJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dworkClient) GetAllJobs(ctx context.Context, in *JobParams, opts ...grpc.CallOption) (*JobStatuses, error) {
	out := new(JobStatuses)
	err := grpc.Invoke(ctx, "/pb.Dwork/GetAllJobs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dwork service

type DworkServer interface {
	// Sends a greeting
	GiveWork(context.Context, *WorkerID) (*WorkUnit, error)
	ReceiveResults(context.Context, *Results) (*Success, error)
	SubmitJob(context.Context, *Job) (*Success, error)
	GetAllJobs(context.Context, *JobParams) (*JobStatuses, error)
}

func RegisterDworkServer(s *grpc.Server, srv DworkServer) {
	s.RegisterService(&_Dwork_serviceDesc, srv)
}

func _Dwork_GiveWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DworkServer).GiveWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dwork/GiveWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DworkServer).GiveWork(ctx, req.(*WorkerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dwork_ReceiveResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Results)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DworkServer).ReceiveResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dwork/ReceiveResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DworkServer).ReceiveResults(ctx, req.(*Results))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dwork_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DworkServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dwork/SubmitJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DworkServer).SubmitJob(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dwork_GetAllJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DworkServer).GetAllJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dwork/GetAllJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DworkServer).GetAllJobs(ctx, req.(*JobParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Dwork",
	HandlerType: (*DworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GiveWork",
			Handler:    _Dwork_GiveWork_Handler,
		},
		{
			MethodName: "ReceiveResults",
			Handler:    _Dwork_ReceiveResults_Handler,
		},
		{
			MethodName: "SubmitJob",
			Handler:    _Dwork_SubmitJob_Handler,
		},
		{
			MethodName: "GetAllJobs",
			Handler:    _Dwork_GetAllJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/dwork.proto",
}

func init() { proto.RegisterFile("pb/dwork.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0xed, 0x24, 0xdb, 0x36, 0xb9, 0xd5, 0x0a, 0x83, 0xc8, 0x18, 0x44, 0xca, 0xec, 0x4b, 0x1e,
	0xb4, 0xc2, 0x8a, 0x1f, 0x20, 0x06, 0x97, 0x06, 0x51, 0x99, 0x58, 0x7c, 0xce, 0x24, 0xb3, 0x38,
	0x6c, 0xd3, 0x09, 0x99, 0xc9, 0x0a, 0x7e, 0x90, 0xaf, 0xbe, 0xf8, 0x81, 0x32, 0x33, 0x49, 0xba,
	0x14, 0x05, 0xdf, 0xce, 0xe9, 0x9c, 0xde, 0x73, 0xef, 0xb9, 0x37, 0xb0, 0x6e, 0xf9, 0xab, 0xfa,
	0xbb, 0xea, 0x6e, 0xb7, 0x6d, 0xa7, 0x8c, 0xc2, 0x41, 0xcb, 0xa9, 0x84, 0x25, 0x13, 0xba, 0x3f,
	0x18, 0x8d, 0x1f, 0xc3, 0x3c, 0x57, 0x7c, 0x97, 0x11, 0xb4, 0x41, 0x69, 0xcc, 0x3c, 0xc1, 0x4f,
	0x60, 0xf1, 0x55, 0x75, 0xb7, 0xbb, 0x8c, 0x04, 0x1b, 0x94, 0x86, 0x6c, 0x60, 0x56, 0xfd, 0x5e,
	0xf5, 0xc7, 0x9a, 0x84, 0x1b, 0x94, 0x46, 0xcc, 0x13, 0x9c, 0x40, 0xf4, 0x41, 0x55, 0xa5, 0x91,
	0xea, 0x48, 0x2e, 0x9c, 0x7e, 0xe2, 0xf4, 0x27, 0x82, 0xc8, 0xfe, 0x79, 0x7f, 0x94, 0xe6, 0x1f,
	0x66, 0x6b, 0x08, 0x26, 0xa3, 0xc0, 0x9b, 0x7f, 0xba, 0xb9, 0xd1, 0xc2, 0x38, 0x97, 0x90, 0x0d,
	0x0c, 0x63, 0xb8, 0x28, 0xe4, 0x0f, 0x31, 0x58, 0x38, 0x6c, 0xb5, 0x85, 0x29, 0x4d, 0xaf, 0xc9,
	0xdc, 0x6b, 0x3d, 0xc3, 0xcf, 0x20, 0xfe, 0x22, 0x1b, 0xa1, 0x4d, 0xd9, 0xb4, 0x64, 0xe1, 0x9e,
	0x4e, 0x3f, 0xd8, 0x4a, 0xef, 0x54, 0x2d, 0xc8, 0xd2, 0xb5, 0xe1, 0x30, 0xbd, 0x84, 0x65, 0xd1,
	0x57, 0x95, 0xd0, 0x1a, 0x93, 0x09, 0xba, 0x46, 0x23, 0x36, 0x52, 0xfa, 0xdc, 0x0f, 0x23, 0xba,
	0x5d, 0x66, 0x8b, 0xec, 0xf7, 0xd3, 0x2c, 0x0e, 0xd3, 0x97, 0x10, 0xe6, 0x8a, 0xdb, 0xa7, 0x8f,
	0x65, 0x23, 0xc6, 0x27, 0x8b, 0x27, 0xcf, 0xe0, 0x9e, 0xe7, 0x0a, 0xe2, 0x5c, 0xf1, 0xcf, 0x65,
	0x57, 0x36, 0x9a, 0xfe, 0x42, 0xb0, 0xca, 0x15, 0xf7, 0x03, 0x08, 0x8d, 0xdf, 0x40, 0x34, 0x62,
	0x82, 0x36, 0x61, 0xba, 0xba, 0x7a, 0xba, 0x6d, 0xf9, 0xf6, 0x9e, 0xe4, 0x84, 0xd9, 0x24, 0x4d,
	0xa4, 0xab, 0x39, 0xc4, 0xf0, 0xb7, 0x46, 0x6c, 0x64, 0xdf, 0xca, 0xae, 0xd6, 0xe3, 0x6e, 0x3d,
	0xfb, 0xcf, 0xdd, 0xc6, 0xa7, 0xdd, 0x5e, 0xfd, 0x46, 0x30, 0xcf, 0xec, 0x69, 0xe1, 0x14, 0xa2,
	0x6b, 0x79, 0x27, 0x6c, 0x36, 0xf8, 0x81, 0xed, 0x72, 0x4c, 0x29, 0x99, 0x98, 0x3d, 0x00, 0x3a,
	0xc3, 0x2f, 0x60, 0xcd, 0x44, 0x25, 0xe4, 0x9d, 0x18, 0x2f, 0x70, 0x65, 0x15, 0x03, 0x49, 0x1c,
	0x19, 0xd3, 0x9e, 0xe1, 0x4b, 0x88, 0x8b, 0x9e, 0x37, 0xd2, 0xd8, 0x54, 0x97, 0xc3, 0xf8, 0xe7,
	0xa2, 0x2d, 0xc0, 0xb5, 0x30, 0x6f, 0x0f, 0x87, 0x5c, 0x71, 0x8d, 0x1f, 0x0e, 0x2a, 0x9f, 0x6a,
	0xf2, 0xe8, 0x2c, 0x33, 0x3a, 0xe3, 0x0b, 0xf7, 0x21, 0xbc, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xe7, 0x9d, 0x8f, 0x41, 0x1a, 0x03, 0x00, 0x00,
}
