// Code generated by protoc-gen-go.
// source: pb/dwork.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/dwork.proto

It has these top-level messages:
	Results
	WorkUnit
	ResultsSuccess
	WorkerID
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Results struct {
	Workid   int32 `protobuf:"varint,1,opt,name=workid" json:"workid,omitempty"`
	Found    bool  `protobuf:"varint,2,opt,name=found" json:"found,omitempty"`
	Location int32 `protobuf:"varint,3,opt,name=location" json:"location,omitempty"`
}

func (m *Results) Reset()                    { *m = Results{} }
func (m *Results) String() string            { return proto.CompactTextString(m) }
func (*Results) ProtoMessage()               {}
func (*Results) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Results) GetWorkid() int32 {
	if m != nil {
		return m.Workid
	}
	return 0
}

func (m *Results) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *Results) GetLocation() int32 {
	if m != nil {
		return m.Location
	}
	return 0
}

// The response message containing the greetings
// https://developers.google.com/protocol-buffers/docs/proto3
type WorkUnit struct {
	Id        int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Offset    int32 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Size      int32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Search    int32 `protobuf:"varint,4,opt,name=search" json:"search,omitempty"`
	Status    int32 `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *WorkUnit) Reset()                    { *m = WorkUnit{} }
func (m *WorkUnit) String() string            { return proto.CompactTextString(m) }
func (*WorkUnit) ProtoMessage()               {}
func (*WorkUnit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WorkUnit) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WorkUnit) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *WorkUnit) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *WorkUnit) GetSearch() int32 {
	if m != nil {
		return m.Search
	}
	return 0
}

func (m *WorkUnit) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *WorkUnit) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ResultsSuccess struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *ResultsSuccess) Reset()                    { *m = ResultsSuccess{} }
func (m *ResultsSuccess) String() string            { return proto.CompactTextString(m) }
func (*ResultsSuccess) ProtoMessage()               {}
func (*ResultsSuccess) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResultsSuccess) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type WorkerID struct {
	UUID string `protobuf:"bytes,1,opt,name=UUID" json:"UUID,omitempty"`
}

func (m *WorkerID) Reset()                    { *m = WorkerID{} }
func (m *WorkerID) String() string            { return proto.CompactTextString(m) }
func (*WorkerID) ProtoMessage()               {}
func (*WorkerID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WorkerID) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func init() {
	proto.RegisterType((*Results)(nil), "pb.Results")
	proto.RegisterType((*WorkUnit)(nil), "pb.WorkUnit")
	proto.RegisterType((*ResultsSuccess)(nil), "pb.ResultsSuccess")
	proto.RegisterType((*WorkerID)(nil), "pb.WorkerID")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Dwork service

type DworkClient interface {
	// Sends a greeting
	GiveWork(ctx context.Context, in *WorkerID, opts ...grpc.CallOption) (*WorkUnit, error)
	ReceiveResults(ctx context.Context, in *Results, opts ...grpc.CallOption) (*ResultsSuccess, error)
}

type dworkClient struct {
	cc *grpc.ClientConn
}

func NewDworkClient(cc *grpc.ClientConn) DworkClient {
	return &dworkClient{cc}
}

func (c *dworkClient) GiveWork(ctx context.Context, in *WorkerID, opts ...grpc.CallOption) (*WorkUnit, error) {
	out := new(WorkUnit)
	err := grpc.Invoke(ctx, "/pb.Dwork/GiveWork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dworkClient) ReceiveResults(ctx context.Context, in *Results, opts ...grpc.CallOption) (*ResultsSuccess, error) {
	out := new(ResultsSuccess)
	err := grpc.Invoke(ctx, "/pb.Dwork/receiveResults", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dwork service

type DworkServer interface {
	// Sends a greeting
	GiveWork(context.Context, *WorkerID) (*WorkUnit, error)
	ReceiveResults(context.Context, *Results) (*ResultsSuccess, error)
}

func RegisterDworkServer(s *grpc.Server, srv DworkServer) {
	s.RegisterService(&_Dwork_serviceDesc, srv)
}

func _Dwork_GiveWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DworkServer).GiveWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dwork/GiveWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DworkServer).GiveWork(ctx, req.(*WorkerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dwork_ReceiveResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Results)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DworkServer).ReceiveResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dwork/ReceiveResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DworkServer).ReceiveResults(ctx, req.(*Results))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Dwork",
	HandlerType: (*DworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GiveWork",
			Handler:    _Dwork_GiveWork_Handler,
		},
		{
			MethodName: "receiveResults",
			Handler:    _Dwork_ReceiveResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/dwork.proto",
}

func init() { proto.RegisterFile("pb/dwork.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x91, 0xcd, 0x6a, 0xc3, 0x30,
	0x0c, 0x80, 0x9b, 0xb4, 0x69, 0x53, 0x6d, 0xe4, 0x20, 0xc6, 0x30, 0x65, 0x8c, 0xe2, 0x53, 0xd8,
	0x21, 0x83, 0xf5, 0x15, 0x02, 0xa3, 0x57, 0x97, 0xb0, 0x73, 0x7e, 0x1c, 0x66, 0xda, 0xc6, 0xc1,
	0x76, 0x3a, 0xd8, 0x73, 0xec, 0x81, 0x87, 0x1d, 0x27, 0xdb, 0x4d, 0x9f, 0xfc, 0x59, 0x96, 0x64,
	0x48, 0xfa, 0xea, 0xb5, 0xf9, 0x92, 0xea, 0x9c, 0xf5, 0x4a, 0x1a, 0x89, 0x61, 0x5f, 0xd1, 0x13,
	0x6c, 0x18, 0xd7, 0xc3, 0xc5, 0x68, 0x7c, 0x84, 0xb5, 0x3d, 0x14, 0x0d, 0x09, 0xf6, 0x41, 0x1a,
	0x31, 0x4f, 0xf8, 0x00, 0x51, 0x2b, 0x87, 0xae, 0x21, 0xe1, 0x3e, 0x48, 0x63, 0x36, 0x02, 0xee,
	0x20, 0xbe, 0xc8, 0xba, 0x34, 0x42, 0x76, 0x64, 0xe9, 0xfc, 0x99, 0xe9, 0x4f, 0x00, 0xf1, 0x87,
	0x54, 0xe7, 0xa2, 0x13, 0x06, 0x13, 0x08, 0xe7, 0x92, 0xa1, 0x68, 0xec, 0x33, 0xb2, 0x6d, 0x35,
	0x37, 0xae, 0x5e, 0xc4, 0x3c, 0x21, 0xc2, 0x4a, 0x8b, 0x6f, 0xee, 0x8b, 0xb9, 0xd8, 0xba, 0x9a,
	0x97, 0xaa, 0xfe, 0x24, 0xab, 0xd1, 0x1d, 0xc9, 0xe5, 0x4d, 0x69, 0x06, 0x4d, 0x22, 0x9f, 0x77,
	0x84, 0x4f, 0xb0, 0x35, 0xe2, 0xca, 0xb5, 0x29, 0xaf, 0x3d, 0x59, 0xef, 0x83, 0x74, 0xc9, 0xfe,
	0x12, 0xf4, 0x05, 0x12, 0x3f, 0xeb, 0x69, 0xa8, 0x6b, 0xae, 0x35, 0x12, 0xd8, 0xe8, 0x31, 0x74,
	0x0d, 0xc6, 0x6c, 0x42, 0xfa, 0x3c, 0x4e, 0xc0, 0xd5, 0x31, 0xb7, 0x9d, 0x15, 0xc5, 0x31, 0x77,
	0xca, 0x96, 0xb9, 0xf8, 0xad, 0x85, 0x28, 0xb7, 0xfb, 0xc1, 0x14, 0xe2, 0x77, 0x71, 0xe3, 0x56,
	0xc6, 0xfb, 0xac, 0xaf, 0xb2, 0xe9, 0xda, 0x6e, 0x26, 0xbb, 0x06, 0xba, 0xc0, 0x03, 0x24, 0x8a,
	0xd7, 0x5c, 0xdc, 0xf8, 0xb4, 0xf1, 0x3b, 0x6b, 0x78, 0xd8, 0xe1, 0x3f, 0xf0, 0xfd, 0xd1, 0x45,
	0xb5, 0x76, 0x5f, 0x75, 0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xdf, 0xbe, 0x23, 0xbc, 0x01,
	0x00, 0x00,
}
